import HardsetCore
import SwiftUI

/// The disclosure behind a number.
///
/// App Review guideline 1.4.1 requires an app to "clearly disclose data and methodology to support
/// accuracy claims relating to health measurements", and to reject the app if the methodology
/// cannot be validated. This view renders an `EvidenceSource` verbatim, which means the disclosure
/// is generated by the same values the arithmetic uses and cannot drift from what the code does.
/// Writing this copy by hand in a settings screen is exactly how the two come apart.
///
/// It is also the brand. An app whose claim is calibrated honesty has to be willing to show the
/// limits of its own numbers on the same screen as the numbers.
public struct MethodologySheet: View {
  private let source: EvidenceSource
  private let certainty: Certainty?

  public init(source: EvidenceSource, certainty: Certainty? = nil) {
    self.source = source
    self.certainty = certainty
  }

  public var body: some View {
    NavigationStack {
      ScrollView {
        VStack(alignment: .leading, spacing: Tokens.Spacing.section) {
          if let certainty {
            HStack(spacing: Tokens.Spacing.tight) {
              Image(systemName: Self.symbol(for: certainty))
              Text(Self.label(for: certainty))
            }
            .font(Tokens.Text.caption)
            .foregroundStyle(Tokens.Color.certainty(Self.level(for: certainty)))
          }

          section("How this is calculated", source.methodology)

          if let validRange = source.validRange {
            // Deliberately its own section rather than a parenthetical. The limits of a number are
            // as much a part of the disclosure as the method.
            section("Where this applies, and where it does not", validRange)
          }

          if let citation = source.citation {
            section("Source", citation, monospaced: true)
          }
        }
        .padding(Tokens.Spacing.regular)
        .frame(maxWidth: .infinity, alignment: .leading)
      }
      .background(Tokens.Color.background)
      .navigationTitle(source.title)
    }
  }

  private func section(_ heading: String, _ body: String, monospaced: Bool = false) -> some View {
    VStack(alignment: .leading, spacing: Tokens.Spacing.snug) {
      Text(heading)
        .font(Tokens.Text.label.weight(.semibold))
      Text(body)
        .font(monospaced ? Tokens.Text.caption.monospaced() : Tokens.Text.label)
        .foregroundStyle(monospaced ? Tokens.Color.textSecondary : Tokens.Color.textPrimary)
        .textSelection(.enabled)
    }
    .frame(maxWidth: .infinity, alignment: .leading)
  }

  /// Maps engine certainty onto the UI's own scale. Kept here so `HardsetUI` does not need the
  /// engine's enum to colour a chip, matching how `CertaintyLevel` is already used.
  static func level(for certainty: Certainty) -> CertaintyLevel {
    switch certainty {
    case .high: .high
    case .moderate: .moderate
    case .low: .low
    case .unevaluated: .unevaluated
    }
  }

  static func label(for certainty: Certainty) -> String { level(for: certainty).label }
  static func symbol(for certainty: Certainty) -> String { level(for: certainty).symbolName }
}

#if DEBUG
  #Preview("Fractional counting") {
    MethodologySheet(source: SetCounting.source, certainty: .moderate)
  }

  #Preview("No target exists") {
    MethodologySheet(source: VolumeAnalyzer.targetSource, certainty: .unevaluated)
  }
#endif
